### Imports ###
from os.path import join
from pandas import read_table

### Config file ###
configfile: join('config', 'config.yaml')

### Setup ###
global_resources = workflow.global_resources

USE_GPU = ('gpus' in global_resources) and (global_resources['gpus'] > 0)

### Input and output variables ###
include: join('rules', 'variables.smk')

### Targets ###
sample_df = read_table(join(config['resources'], 'samples_list.tsv'))

ALL_SLIDES_ZARR = expand(
    join('<results>', 'converted_zarr', '{patient_id}', '{slide}.zarr'),
    zip,
    patient_id=sample_df['patient'],
    slide=sample_df['slide'],
)

### Rules ###
rule all:
    input:
        ALL_SLIDES_ZARR,
    default_target:
        True

include: join('rules', 'preprocessing.smk')