### Imports ###
from os.path import join
from pandas import read_table

### Config file ###
configfile: join('config', 'config.yaml')

### Setup ###
global_resources = workflow.global_resources

if 'gpus' in global_resources and global_resources['gpus'].value > 0:
    from lib.gpu_manager import GpuManager

    gpu_manager = GpuManager(config['gpu_ids'])

    USE_GPU = True
else:
    USE_GPU = False

### Input and output variables ###
include: join('rules', 'variables.smk')

### Targets ###
def get_network_targets(wc):
    with checkpoints.select_best_slides.get().output['mapping'].open() as f:
        df = read_table(f)
        return expand(
            SPOT_INDEGREES,
            zip,
            patient_id=df['patient_id'][:10],
            slide=df[config['slide_selection']][:10],
        )

### Rules ###
rule all:
    input:
        get_network_targets,
    default_target:
        True

include: join('rules', 'preprocessing.smk')
include: join('rules', 'networks.smk')