# Path variables
resources: &RSRC "resources"
results: &RSLT "results"
pathvars:
  resources: *RSRC
  results: *RSLT
  counts: "<resources>/raw_counts"
  priors: "<resources>/priors"
  scripts: "workflow/scripts"
  templates: "workflow/sisana_templates"
# Preprocessing settings
slide_selection: "best_genes_median"
min_counts_per_spot: [ 0 ]
clustering_resolutions: [ 1.0 ]
filter_ratio_threshold: [ 0.1 ]
# Network generation settings
gpu_ids: [ 2, 3 ]
lioness_threads: 8
# Analysis settings
modalities: [ "expression", "indegrees", "outdegrees" ]
gsea_modalities: [ "expression", "indegrees" ]
gene_sets:
  Hallmarks: "<resources>/gene_sets/h.all.v2025.1.Hs.symbols.gmt"
  Biological_process: "<resources>/gene_sets/c5.go.bp.v2025.1.Hs.symbols.gmt"
  KEGG_Medicus: "<resources>/gene_sets/c2.cp.kegg_medicus.v2025.1.Hs.symbols.gmt"
  Reactome: "<resources>/gene_sets/ReactomePathways.gmt"
