resources: &RSRC "resources"
results: &RSLT "results"
pathvars:
  resources: *RSRC
  results: *RSLT
  counts: "<resources>/raw_counts"
  priors: "<resources>/priors"
  scripts: "workflow/scripts"
slide_selection: "best_genes_median"
min_counts_per_spot: [ 0 ]
gpu_ids: [ 3 ]
clustering_resolutions: [ 1.0 ]
filter_ratio_threshold: [ 0.1 ]
lioness_threads: 8
